# Generated by Django 4.2.13 on 2024-06-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_date'], 'verbose_name_plural': 'Education Information'},
        ),
    ]
