# Generated by Django 4.2.13 on 2024-06-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_education_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
