# Generated by Django 4.2.13 on 2024-06-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='title',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
