# Generated by Django 4.2.13 on 2024-07-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_personalinfo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='diploma_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='technologies_learned',
            field=models.TextField(blank=True, null=True),
        ),
    ]
