# Generated by Django 4.2.13 on 2024-06-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='excerpt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='../code_iozqi5', upload_to='images/'),
        ),
    ]
