# Generated by Django 4.2.13 on 2024-06-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
