# Generated by Django 4.2.13 on 2024-06-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalskill',
            name='category',
            field=models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('libraries', 'Libraries'), ('database', 'Database'), ('version_control', 'Version Control'), ('methodologies', 'Methodologies'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
